# Generated by Django 4.0.4 on 2023-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_card_set_alter_card_answer_alter_card_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsets',
            name='checked',
            field=models.BooleanField(default=0),
        ),
    ]
