# Generated by Django 4.0.4 on 2023-04-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsets',
            name='set_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
