# Generated by Django 4.0.4 on 2023-04-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardsets_set_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cards.cardsets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
